using System;
using System.Linq;
using System.Runtime.InteropServices;
using Server.Items;
using System.Collections.Generic;

namespace Server.Misc
{
 		
        class ClasseInit 
        {
				public static void Configure()
				{
	
	
	//	public Classe(int ClasseID,	string name, int classLvl, int armor, bool hidden, List<int> evolution, 	Dictionary<SkillName, double> skill	)
	
			  	Classe.RegisterClasse(new Classe(0, "Aucune",0,0,true,new List<int>(), new Dictionary<SkillName, double>() {  }));
				Classe.RegisterClasse(new Classe(1, "Humain",0,0,false, new List<int>(){4,5,6,7,8}, new Dictionary<SkillName, double>() { })); 
				Classe.RegisterClasse(new Classe(2, "Vampire",0,0,false, new List<int>(){}, new Dictionary<SkillName, double>() { })); 
				Classe.RegisterClasse(new Classe(3, "Lycan",0,0,false, new List<int>(){}, new Dictionary<SkillName, double>() { })); 
				Classe.RegisterClasse(new Classe(4, "Recrue",1,2,false, new List<int>(){9,14}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.Parry, 50}, {SkillName.Healing, 50}, {SkillName.MagicResist, 50}, {SkillName.Tactics, 50}, {SkillName.Swords, 50}, {SkillName.Macing, 50}, {SkillName.Fencing, 50}, {SkillName.Wrestling, 50}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(5, "Apprenti",1,1,false, new List<int>(){21}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.EvalInt, 50}, {SkillName.Magery, 50}, {SkillName.MagicResist, 50}, {SkillName.Meditation, 50}, })); 
				Classe.RegisterClasse(new Classe(6, "Chasseur",1,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.Healing, 50}, {SkillName.MagicResist, 50}, {SkillName.Tactics, 50}, {SkillName.Archery, 50}, {SkillName.Tracking, 50}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(7, "Troubadour",1,1,false, new List<int>(){37}, new Dictionary<SkillName, double>() { {SkillName.Peacemaking, 50}, {SkillName.Discordance, 50}, {SkillName.Provocation, 50}, {SkillName.MagicResist, 50}, {SkillName.Tactics, 50}, {SkillName.Musicianship, 50}, {SkillName.Focus, 50}, {SkillName.Throwing, 50}, })); 
				Classe.RegisterClasse(new Classe(8, "Voyageur",1,1,false, new List<int>(){44}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.AnimalLore, 50}, {SkillName.Healing, 50}, {SkillName.Herding, 50}, {SkillName.AnimalTaming, 50}, {SkillName.Veterinary, 50}, {SkillName.Macing, 50}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(9, "Combattant",2,4,false, new List<int>(){10,12}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 75}, {SkillName.Parry, 75}, {SkillName.Healing, 75}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 75}, {SkillName.Swords, 75}, {SkillName.Macing, 75}, {SkillName.Focus, 75}, })); 
				Classe.RegisterClasse(new Classe(10, "Champion",3,5,false, new List<int>(){11}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.Parry, 85}, {SkillName.Healing, 85}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Swords, 85}, {SkillName.Macing, 85}, {SkillName.Focus, 85}, {SkillName.Bushido, 85}, })); 
				Classe.RegisterClasse(new Classe(11, "Maitre d’arme",4,6,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.Parry, 100}, {SkillName.Healing, 100}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Focus, 100}, {SkillName.Bushido, 100}, })); 
				Classe.RegisterClasse(new Classe(12, "Templier",3,5,false, new List<int>(){13}, new Dictionary<SkillName, double>() { {SkillName.Parry, 85}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Swords, 85}, {SkillName.Macing, 85}, {SkillName.Focus, 85}, {SkillName.Chivalry, 85}, })); 
				Classe.RegisterClasse(new Classe(13, "Paladin",4,6,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Parry, 100}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Focus, 100}, {SkillName.Chivalry, 100}, })); 
				Classe.RegisterClasse(new Classe(14, "Crapule",2,3,false, new List<int>(){15, 17, 19}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.Parry, 50}, {SkillName.Healing, 50}, {SkillName.Hiding, 75}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 50}, {SkillName.Swords, 75}, {SkillName.Fencing, 75}, {SkillName.Stealth, 75}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(15, "Tueur",3,4,false, new List<int>(){16}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.Healing, 50}, {SkillName.Hiding, 85}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 85}, {SkillName.Poisoning, 85}, {SkillName.Fencing, 85}, {SkillName.Stealth, 85}, {SkillName.Focus, 85}, })); 
				Classe.RegisterClasse(new Classe(16, "Assassin",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.Healing, 50}, {SkillName.Hiding, 100}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 100}, {SkillName.Poisoning, 100}, {SkillName.Fencing, 100}, {SkillName.Stealth, 100}, {SkillName.Focus, 100}, })); 
				Classe.RegisterClasse(new Classe(17, "Ninja",3,4,false, new List<int>(){18}, new Dictionary<SkillName, double>() { {SkillName.Parry, 85}, {SkillName.Hiding, 85}, {SkillName.MagicResist, 75}, {SkillName.Swords, 85}, {SkillName.Fencing, 85}, {SkillName.Stealth, 85}, {SkillName.Focus, 85}, {SkillName.Ninjitsu, 85}, {SkillName.Throwing, 85}, })); 
				Classe.RegisterClasse(new Classe(18, "Shinobi",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Parry, 100}, {SkillName.Hiding, 100}, {SkillName.MagicResist, 75}, {SkillName.Swords, 100}, {SkillName.Fencing, 100}, {SkillName.Stealth, 100}, {SkillName.Focus, 100}, {SkillName.Ninjitsu, 100}, {SkillName.Throwing, 100}, })); 
				Classe.RegisterClasse(new Classe(19, "Cambrioleur",3,3,false, new List<int>(){20}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.DetectHidden, 85}, {SkillName.Healing, 50}, {SkillName.Hiding, 85}, {SkillName.Lockpicking, 85}, {SkillName.Tactics, 85}, {SkillName.Snooping, 85}, {SkillName.Poisoning, 70}, {SkillName.Stealing, 85}, {SkillName.Tracking, 85}, {SkillName.Fencing, 85}, {SkillName.Stealth, 85}, {SkillName.RemoveTrap, 85}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(20, "Voleur",4,3,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.DetectHidden, 100}, {SkillName.Healing, 50}, {SkillName.Hiding, 100}, {SkillName.Lockpicking, 100}, {SkillName.Tactics, 100}, {SkillName.Snooping, 100}, {SkillName.Poisoning, 70}, {SkillName.Stealing, 100}, {SkillName.Tracking, 100}, {SkillName.Fencing, 100}, {SkillName.Stealth, 100}, {SkillName.RemoveTrap, 100}, {SkillName.Focus, 50}, })); 
				Classe.RegisterClasse(new Classe(21, "Magicien",2,1,false, new List<int>(){22,24,40}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 75}, {SkillName.EvalInt, 75}, {SkillName.Magery, 75}, {SkillName.MagicResist, 75}, {SkillName.Meditation, 75}, })); 
				Classe.RegisterClasse(new Classe(22, "Sorcier Noir",3,2,false, new List<int>(){23}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.EvalInt, 85}, {SkillName.Magery, 85}, {SkillName.MagicResist, 85}, {SkillName.Poisoning, 85}, {SkillName.SpiritSpeak, 85}, {SkillName.Meditation, 85}, {SkillName.Necromancy, 85}, })); 
				Classe.RegisterClasse(new Classe(23, "Necromancien",4,3,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.EvalInt, 100}, {SkillName.Magery, 100}, {SkillName.MagicResist, 100}, {SkillName.Poisoning, 100}, {SkillName.SpiritSpeak, 100}, {SkillName.Meditation, 100}, {SkillName.Necromancy, 100}, })); 
				Classe.RegisterClasse(new Classe(24, "Ermite",3,2,false, new List<int>(){25}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.EvalInt, 85}, {SkillName.Magery, 85}, {SkillName.MagicResist, 85}, {SkillName.Meditation, 85}, {SkillName.Spellweaving, 85}, })); 
				Classe.RegisterClasse(new Classe(25, "Druide",4,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.EvalInt, 100}, {SkillName.Magery, 100}, {SkillName.MagicResist, 100}, {SkillName.Meditation, 100}, {SkillName.Spellweaving, 100}, })); 
				Classe.RegisterClasse(new Classe(26, "spiritualiste",3,2,false, new List<int>(){27}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.EvalInt, 85}, {SkillName.Magery, 85}, {SkillName.MagicResist, 85}, {SkillName.Meditation, 85}, {SkillName.Mysticism, 85}, })); 
				Classe.RegisterClasse(new Classe(27, "Mystique",4,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.EvalInt, 100}, {SkillName.Magery, 100}, {SkillName.MagicResist, 100}, {SkillName.Meditation, 100}, {SkillName.Mysticism, 100}, })); 
				Classe.RegisterClasse(new Classe(28, "Archer",2,3,false, new List<int>(){29,31,33,35}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 75}, {SkillName.Healing, 75}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 75}, {SkillName.Archery, 75}, {SkillName.Tracking, 75}, {SkillName.Focus, 75}, })); 
				Classe.RegisterClasse(new Classe(29, "Eclaireur",3,4,false, new List<int>(){30}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.DetectHidden, 85}, {SkillName.Healing, 85}, {SkillName.Hiding, 75}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Archery, 85}, {SkillName.Tracking, 85}, {SkillName.Swords, 75}, {SkillName.Fencing, 75}, {SkillName.Stealth, 75}, {SkillName.RemoveTrap, 85}, {SkillName.Focus, 85}, })); 
				Classe.RegisterClasse(new Classe(30, "Pisteur",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.DetectHidden, 100}, {SkillName.Healing, 100}, {SkillName.Hiding, 85}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Archery, 100}, {SkillName.Tracking, 100}, {SkillName.Swords, 85}, {SkillName.Fencing, 85}, {SkillName.Stealth, 85}, {SkillName.RemoveTrap, 100}, {SkillName.Focus, 100}, })); 
				Classe.RegisterClasse(new Classe(31, "Forestier",3,4,false, new List<int>(){32}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 85}, {SkillName.Healing, 85}, {SkillName.Herding, 85}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 75}, {SkillName.Archery, 85}, {SkillName.AnimalTaming, 85}, {SkillName.Veterinary, 85}, {SkillName.Focus, 85}, })); 
				Classe.RegisterClasse(new Classe(32, "Rodeur",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.AnimalLore, 100}, {SkillName.Healing, 100}, {SkillName.Herding, 100}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 75}, {SkillName.Archery, 100}, {SkillName.AnimalTaming, 100}, {SkillName.Veterinary, 100}, {SkillName.Focus, 100}, })); 
				Classe.RegisterClasse(new Classe(33, "Franc Tireur",3,4,false, new List<int>(){34}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.Healing, 85}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Archery, 85}, {SkillName.Focus, 85}, {SkillName.Bushido, 85}, })); 
				Classe.RegisterClasse(new Classe(34, "Maître Archer",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.Healing, 100}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Archery, 100}, {SkillName.Focus, 100}, {SkillName.Bushido, 100}, })); 
				Classe.RegisterClasse(new Classe(35, "Archer devoué",3,4,false, new List<int>(){36}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.Healing, 85}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Archery, 85}, {SkillName.Focus, 85}, {SkillName.Chivalry, 85}, })); 
				Classe.RegisterClasse(new Classe(36, "Archer Fanatique",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.Healing, 100}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Archery, 100}, {SkillName.Focus, 100}, {SkillName.Chivalry, 100}, })); 
				Classe.RegisterClasse(new Classe(37, "Baladin",2,2,false, new List<int>(){38,40,42}, new Dictionary<SkillName, double>() { {SkillName.Peacemaking, 75}, {SkillName.Discordance, 75}, {SkillName.Provocation, 75}, {SkillName.MagicResist, 75}, {SkillName.Tactics, 75}, {SkillName.Musicianship, 75}, {SkillName.Focus, 75}, {SkillName.Throwing, 75}, })); 
				Classe.RegisterClasse(new Classe(38, "Chanteur Lame",3,4,false, new List<int>(){39}, new Dictionary<SkillName, double>() { {SkillName.Peacemaking, 85}, {SkillName.Discordance, 85}, {SkillName.Provocation, 85}, {SkillName.MagicResist, 85}, {SkillName.Tactics, 85}, {SkillName.Musicianship, 85}, {SkillName.Swords, 85}, {SkillName.Focus, 85}, {SkillName.Throwing, 85}, })); 
				Classe.RegisterClasse(new Classe(39, "Danseur de lame",4,4,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Peacemaking, 100}, {SkillName.Discordance, 100}, {SkillName.Provocation, 100}, {SkillName.MagicResist, 100}, {SkillName.Tactics, 100}, {SkillName.Musicianship, 100}, {SkillName.Swords, 100}, {SkillName.Focus, 100}, {SkillName.Throwing, 100}, })); 
				Classe.RegisterClasse(new Classe(40, "Menestrel",3,2,false, new List<int>(){41}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.Peacemaking, 85}, {SkillName.Discordance, 85}, {SkillName.EvalInt, 85}, {SkillName.Provocation, 85}, {SkillName.Magery, 85}, {SkillName.MagicResist, 85}, {SkillName.Musicianship, 85}, {SkillName.Meditation, 85}, })); 
				Classe.RegisterClasse(new Classe(41, "Barde",4,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.Peacemaking, 100}, {SkillName.Discordance, 100}, {SkillName.EvalInt, 100}, {SkillName.Provocation, 100}, {SkillName.Magery, 100}, {SkillName.MagicResist, 100}, {SkillName.Musicianship, 100}, {SkillName.Meditation, 100}, })); 
				Classe.RegisterClasse(new Classe(42, "Barde-Dresseur",3,2,false, new List<int>(){43}, new Dictionary<SkillName, double>() { {SkillName.AnimalLore, 85}, {SkillName.Peacemaking, 85}, {SkillName.Discordance, 85}, {SkillName.Healing, 85}, {SkillName.Herding, 85}, {SkillName.Provocation, 85}, {SkillName.MagicResist, 85}, {SkillName.Musicianship, 85}, {SkillName.AnimalTaming, 85}, {SkillName.Veterinary, 85}, {SkillName.Wrestling, 85}, {SkillName.Focus, 85}, })); 
				Classe.RegisterClasse(new Classe(43, "Barde-Menestrel",4,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.AnimalLore, 100}, {SkillName.Peacemaking, 100}, {SkillName.Discordance, 100}, {SkillName.Healing, 100}, {SkillName.Herding, 100}, {SkillName.Provocation, 100}, {SkillName.MagicResist, 100}, {SkillName.Musicianship, 100}, {SkillName.AnimalTaming, 100}, {SkillName.Veterinary, 100}, {SkillName.Wrestling, 100}, {SkillName.Focus, 100}, })); 
				Classe.RegisterClasse(new Classe(44, "Compagnon",2,2,false, new List<int>(){31,42,45}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 75}, {SkillName.AnimalLore, 75}, {SkillName.Healing, 75}, {SkillName.Herding, 75}, {SkillName.AnimalTaming, 75}, {SkillName.Veterinary, 75}, {SkillName.Macing, 75}, {SkillName.Focus, 75}, })); 
				Classe.RegisterClasse(new Classe(45, "Mentor",3,2,false, new List<int>(){46}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 85}, {SkillName.EvalInt, 85}, {SkillName.Healing, 85}, {SkillName.Herding, 85}, {SkillName.Magery, 85}, {SkillName.MagicResist, 85}, {SkillName.AnimalTaming, 85}, {SkillName.Veterinary, 85}, {SkillName.Meditation, 85}, })); 
				Classe.RegisterClasse(new Classe(46, "Shaman",4,2,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.AnimalLore, 100}, {SkillName.EvalInt, 100}, {SkillName.Healing, 100}, {SkillName.Herding, 100}, {SkillName.Magery, 100}, {SkillName.MagicResist, 100}, {SkillName.AnimalTaming, 100}, {SkillName.Veterinary, 100}, {SkillName.Meditation, 100}, })); 


		/*				Classe.RegisterClasse(new Classe(1, "Forgeron",new Dictionary<SkillName, double>() 
						{  
							{SkillName.Blacksmith, 100},
							{SkillName.Mining, 100},
							{SkillName.ArmsLore, 100}
						}));
*/
				}
		}
}
